// <auto-generated />
namespace Creatures3.Module.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class b2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(b2));
        
        string IMigrationMetadata.Id
        {
            get { return "202005160423300_b2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
